language: android

jdk:
    - oraclejdk8
    - openjdk8

android:
  components:
    - android-26

    # Additional components
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
    - addon-google_apis-google-26

before_script:
    - touch /usr/local/android-sdk/licenses/android-sdk-license
    - echo "\nd56f5187479451eabf01fb78af6dfcb131a6481e" >> /usr/local/android-sdk/licenses/android-sdk-license

script: 
    - ./gradlew clean desktop:dist
    - ./gradlew clean android:build

after_success:
    - chmod +x upload-build.sh
    - ./upload-build.sh
