name: Java CI

on: [push, pull_request]

jobs:
  buildJava14:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14
    - name: Run unit tests with gradle and Java 14
      run: ./gradlew compileJava
    - name: Upload desktop jar for testing
      uses: actions/upload-artifact@v2
      with:
        name: Desktop jar (zipped)
        path: desktop/build/libs/Mindustry.jar
  buildJava15:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 15
      uses: actions/setup-java@v1
      with:
        java-version: 15
    - name: Run unit tests with gradle and Java 15
      run: ./gradlew compileJava
