name: iOS Build
on: [push, pull_request]

jobs:
  build:
    name: Build and upload Mindustry.
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: 'macos-12'
            version: '14.2'

    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup Java 17  # Use a newer Java version
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'  # Use Java 17 or higher

      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Step one
        run: chmod +x ./gradlew

      - name: Step two
        run: ./gradlew pack -PnoLocalArc=true

      - name: Step three
        run: ./gradlew --stacktrace :ios:deploy -Probovm.iosSkipSigning=true -PnoLocalArc=true

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: Mindustry iOS
          path: ./Mindustry.ipa
