name: Tests

on: [push]

jobs:
  buildJava14:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 14
      uses: actions/setup-java@v1
      with:
        java-version: 14
    - name: Run unit tests
      run: ./gradlew test
    - name: Trigger BE build
      run: |
        echo "Cloning..."
        git clone --depth=1 --branch=master https://github.com/Anuken/MindustryBuilds ../MindustryBuilds
        echo "Done cloning."
        cd ../MindustryBuilds
        git tag ${GITHUB_RUN_NUMBER}
        git config --global user.name "Build Uploader"
        git push https://Anuken:${{ secrets.GITHUB_TOKEN }}@github.com/Anuken/MindustryBuilds ${GITHUB_RUN_NUMBER}
